camera:
  location:
    x: 0.4218615095128841
    y: -1.6935155668040347
    z: 1.3677984185430894
  rotation:
    x: 1.5707999467849731
    y: 0
    z: 0.4885209146635999
character: Suzie
floor: grey_tiling
light:
  energy:
    - 24.038196915670017
    - 21.502321834197044
    - 24.657515585387706
  locations:
    - x: -0.09416975336266567
      y: 3.253973589400958
    - x: 1.8705170564771236
      y: 3.1125638659699755
    - x: 3.596400536632994
      y: 3.1664747597187315
  rotations:
    - x: 0.02663749248276688
      y: 0.002507853593350573
    - x: 0.03990013629823455
      y: 0.05090408839148211
    - x: 0.02532687961859419
      y: 0.06925096190615436
  types:
    - AREA
    - SPOT
    - POINT
render_state: finish
wall_texture:
  distortion: -0.084740384623965
  rgba:
    - 0.4868909635559491
    - 0.5016070916047533
    - 0.47783415323834044
    - 1
  roughness: 0.8537950893667439
  scale: 0.09259857869890885
